---
title: "Social Survey"
author: "Put your name here!"
date: "put the date here"
output:
  html_document: default
---

```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
source("Import_GSS_2014_haven.R")
```
<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->   

####This study deals with questions about possible relationships between gun ownership and race, sex, political views, opinions on capitol punishment and belief in god. The data is from the 2014 general social survey.



# Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

The data for the social survey has 3,842 observations with 12 different variables all from 2014 data. First the data needed to be organized, so the data was trimmed. An already made R code was used from another file. The select function from the dyplr package extracted the variables that will be used for analysis. The mutate function was used to create three variables for education level. The revalue function was used to organize the data in a better fashion in the following ways: 

-The political views responses were extremely liberal, slightly liberal, extremely conservative, slightly conservative, IAP, and dk. IAP and dk are replaced with value NA

-The responses for belief in God were don't believe and no way to find out changed to no and know God exists was changed to yes. The values some higher power, believe sometimes, believe but doubts and dk were changed to maybe. The response IAP was changed to NA 

-The capital punishment responses yes and no stayed the same. The responses IAP and dk were changed to NA. 

Variable analysis: 

-Belief in God is a factor variable with four levels: no, yes, maybe, and NA. 

-Race is a factor variable with three levels: white, black and other. 

-Capital punishment is a factor variable with three levels: na, yes, and no.

-Sex is a factor variable with two levels: male and female. 

-Political views is a factor variable with three levels: liberals, moderates and conservatives.   
 
All the NA responses will be ommitted when looking at the data. The data will be looked at numerically and graphically. The barcharts will be used for graphical and a two-way table for numerical results. The t-test will be used for the inferential results. 

#Results

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Descriptive Results

### Graphical Descriptive Results

<!--Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question!-->

### Numerical Descriptive Results

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->

# Inferential Results

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variables causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
